import {
  DOCUMENT_ALLOWED_EXTENSIONS,
  DOCUMENT_ALLOWED_MIME_TYPES,
  DOCUMENT_MAX_FILE_SIZE_BYTES,
  DOCUMENT_MAX_TEXT_CHARS,
} from '../documents/document-upload.constants';

export const CV_MAX_FILE_SIZE_BYTES = DOCUMENT_MAX_FILE_SIZE_BYTES;
export const CV_MAX_ACTIVE_PER_CANDIDATE = 10;
export const CV_MAX_TEXT_CHARS = DOCUMENT_MAX_TEXT_CHARS;

export const CV_ALLOWED_MIME_TYPES = DOCUMENT_ALLOWED_MIME_TYPES;

export const CV_ALLOWED_EXTENSIONS = DOCUMENT_ALLOWED_EXTENSIONS;
